version: "3.9"

services:

  #################################################
  # PostgreSQL
  #################################################

  postgres:
    image: postgres:16
    container_name: banking_postgres
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - banking_network


  #################################################
  # PGADMIN
  #################################################

  pgadmin:
    image: dpage/pgadmin4
    container_name: banking_pgadmin
    restart: always

    env_file:
      - .env

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"

    depends_on:
      - postgres

    networks:
      - banking_network


  #################################################
  # AIRFLOW DATABASE
  #################################################

  airflow-db:
    image: postgres:16
    container_name: airflow_postgres
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - airflow_postgres:/var/lib/postgresql/data

    networks:
      - banking_network


  #################################################
  # AIRFLOW
  #################################################

  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: banking_airflow

    restart: always

    env_file:
      - .env

    depends_on:
      - airflow-db

    ports:
      - "8080:8080"

    volumes:
      # Mount entire project
      - ./:/opt/airflow/project

      # DAGs
      - ./airflow/dags:/opt/airflow/dags

      # Logs
      - ./airflow/logs:/opt/airflow/logs

    working_dir: /opt/airflow/project

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username ${AIRFLOW_ADMIN_USERNAME}
      --password ${AIRFLOW_ADMIN_PASSWORD}
      --firstname Admin
      --lastname User
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL} || true &&
      airflow standalone
      "

    networks:
      - banking_network


#################################################
# NETWORK
#################################################

networks:
  banking_network:


#################################################
# VOLUMES
#################################################

volumes:
  postgres_data:
  airflow_postgres: